name: terraform-remote-state
description: Retrieve remote state from a backend
author: Daniel Flook

inputs:
  backend_type:
    description: The backend plugin name
    required: true
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:6eb92df54c85722304d526e6b724f987f1eb4c3437ad17655f88a842f02ca291
  entrypoint: /entrypoints/remote-state.sh

branding:
  icon: globe
  color: purple
